### ISSUE TITLE
Force ids to be more spreadsheet friendly?

### ISSUE THREAD

**Issue by shiffer1** [caporaso-lab/cual-id#42]
John and I have been discussing whether this is a worthwhile thing to do. John doesn't want to end up supporting every spreadsheet program's weird data typing as it is read in, but perhaps some general things can be done without going overboard. John was hoping to get input from others. 

I noticed when I create the ids when the character "e" is followed by numbers or when the id begins with 0 or any number it causes it to be misread by Excel. Most likely people will create the ids and put them in their metadata spreadsheet. I was wondering how difficult it would be to set rules governing the random creation that disallowed a number directly after "e" and starting with 0 or any number. I am sure that this would reduce the number of ids that can be created for a given length but could be an improvement. 
There is also the issue of ids being read in as a date. A simple solution could be that all ids must have at least one letter (or perhaps even better must begin with a letter). 

Thoughts on these ideas?
Arron

**Comment by gregcaporaso** [comment]
What if there was an option to instead output the ids wrapped in quotes? Would that address this issue? Or, is it fixed if you change the format of the cell to *text* (or whatever the equivalent is in the Spreadsheet program that you're using), in which case we could address this with better documentation? I share @johnchase's concern that there are just an endless number of these rules.

**Comment by shiffer1** [comment]
This could solve the initial read in of the values, but once those values have been input to a sample metadata sheet or read again as a csv (by perhaps sharing the file) the issue arises a second time. Additionally, for the EXMP project people are inputting these codes themselves. When I download that information from REDCap it will not have the quote wrapping and hence the problem still arises. 

While talking with Jai he mentioned that perhaps e should not be an allowable character just like o is not. That would solve quite a bit of problems. 
I believe that the omission of e and the insistence of a letter solve pretty much all the problems I have seen with importing data.

**Comment by ebolyen** [comment]
Removing `e` and numbers from the start would limit an already very limited set of IDs, we'd have to run some benchmarks to see if you can still generate enough possible ids in a reasonable time-frame.

**Comment by johnchase** [comment]
To elaborate on @ebolyen's comment the cualids are truncated UUIDs, in order to disallow characters we would need to generate IDs and then discard them if they contained the illegal character which could really hurt performance.

At the risk of getting on a soapbox, I think it is a mistake to modify the IDs as to be spreadhseet friendly because it could give a false sense of security, the data would still have to be checked for any edge cases that we missed and if you already have to define the data type on import what would be the reason to discard IDs in the first place? Furthermore I would argue that *any* data read in by excel, not just cualids, should always be thoroughly evaluated for modifications. [Here](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-016-1044-7) is another example of the problems that can arise with excel.

I think the solution here is when you import data into excel to use (on a mac)  `file > Import...` which will bring up the import wizard. There will be a few dialogue boxes that appear, in one of them there is a checkbox that lets you select the data type as `text` selecting this will import the data without modifying the format at all

**Comment by shiffer1** [comment]
I will try out this option. Perhaps we can point this out in the docs for cualid. It may be the best option. 
Quick question is 0 allowed in the ids?

**Comment by shiffer1** [comment]
In that article it states that google sheets does not perform the auto change and they are protected from change when moved into excel from google sheets. I will try this out on a couple data sets as well.

**Comment by johnchase** [comment]
@shiffer1 Yes, 0-9 and a-f are the characters used in uuids

**Comment by shiffer1** [comment]
Hey John,
Thanks for the clarification.
Arron

**Comment by shiffer1** [comment]
Hello Again, 
As I have been working with these again I wanted to revisit this issue.
Just to reiterate, as it has been a while, the problems are when opening a metadata sheet that contains cual-ids (or any alpha-numeric ids) in Excel or Google Sheets are:

A cual-id with an e followed by a number causes an exponent:
      such as 891e3 would be read in as 891000
A cual-id with leading zeroes is read in by dropping the leading zeroes:
     such as 04567 would be read in as 4567
Any cual-id that is all numbers is identified as a number as opposed to text.
 
Above we offered the solution of using importing. I used the import functions in both Excel and Google Sheets and this works well. It is a little bit technical and I worry about some folks ability to deal with it without a nice set of instructions. I definitely think we should provide some language on how to handle this. We currently recommend Keemei for verifying metadata sheets and I talked with @jairideout about this yesterday. We should have instructions in the tool descriptions for how to import these documents into Excel and Google Sheets in conjunction with caul-ids as we recommend both of these tools. 

All this being said, I think it may be worth revisiting the issue of whether to make adjustments to cual-ids allowed characters. The issue could be considered solved due to the fact that we have a work around by importing, however, it only takes one click of a button to undo the formatting of the cual-ids. I think we should consider that many of the people we are handing these ids off to (lab work, sequencing centers, etc.) may not have a great deal of technical aptitude and we are putting the onus of making sure the files are imported instead of just opened on the user to make sure it is done properly. While I agree we want to avoid making exceptions for a bunch tools, both Excel and Google Sheets are widely used by the community at large, which of course includes the labs and sequencing centers. 

I believe a simple fix of disallowing the use of the e character would solve 90% of the problems associated with just opening the files. The problems of all numbers or leading zeroes is rather minor as these can be easily interpreted.

I believe we need to either make this exception or provide proper instructions on both the cual-id and keemei docs or do both of these things. Thoughts?

**Comment by johnchase** [comment]
@shiffer1 I can certainly understand the desire to make things easier, and safer, your thoughts on this are appreciated. I'll admit I'm hesitant to attempt to account for what are IMHO shortcomings of spreadsheet software. I think my fear is giving a false sense of security, for example if we had a flag that was `excel_safe` we would need to account for every edge case of how excel interprets data which is beyond the scope of this project, or change the flag to `excel_sort_of_safe` at which point the user should still check their data on import making the end result identical as if there were no flag in the first place.

cual-ids are hexadecimal characters, limiting this farther affects the probability of a collision for two IDs and will reduce performance as the IDs are generated from UUIDs meaning IDs will be generated and then discarded. Using standard hexadecimal characters does not seem inappropriate to me. They are used for widely in science and computing (colors, uuids, mongodb object ids etc.); cual-id seems to be the norm rather than the exception. 

I am not opposed to making the IDs spreadsheet safe, but to be honest I don't know of a way to implement it that makes sense, which is probably due in part to the fact that neither excel of google sheets make a ton of sense to me...

**Comment by johnchase** [comment]
I don't think that limiting characters is an appropriate solution. If there are other suggestions please open an issue for those
